dataset:
  name: citeseer
  split: [0.6,0.2,0.2]
  feature_select: random
train:
  batch_size: 256
  patience: 3
  repeat: 5
model:
  num_sample: 0
  cuda: True
  beta: 0.0
  interval: 0.3
  r: 7
  name: ncgnn
  gcn: True
  hidden: 128
optim:
  lr: 0.001
  epochs: 500
  
  
