task_path: /home/zhihao/Document/gnn_fd/graphSage/split/multihead/NCGNN_reorderedge/
dataset:
  name: cora
  split: [0.6,0.2,0.2]
  path: /home/zhihao/Document/gnn_fd/graphSage/data/
  task: node
  transductive: True
train:
  batch_size: 256
  patience: 3
  repeat: 5
model:
  num_sample: 0
  cuda: True
  beta: 0.6
  interval: 0.2
  r: 10
  name: ncgnn
  gcn: True
  hidden: 128
optim:
  lr: 0.001
  epochs: 500
  
  
