path_result: /home/zhihao/Document/gnn_fd/graphSage/split/multihead/NCGNN_reorderedge/results/
dataset:
  name: amazon_computer
  split: [0.6,0.2,0.2]
  path: /home/zhihao/Document/gnn_fd/graphSage/data/
  task: node
  transductive: True
  feature_select: feat_importance
train:
  batch_size: 2048
  patience: 3
  repeat: 5
model:
  num_sample: 0
  cuda: True
  beta: 0.0
  interval: 0.2
  r: 6
  name: ncgnn
  gcn: True
  hidden: 128
optim:
  lr: 0.01
  epochs: 500
  
  
