task_path: /home/zhihao/Document/gnn_fd/graphSage/split/multihead/NC-GNN/
dataset:
  name: academic_py
  split: [0.6,0.2,0.2]
  path: /home/zhihao/Document/gnn_fd/graphSage/data/
  task: node
  transductive: True
train:
  batch_size: 2048
  patience: 5
  repeat: 5
model:
  num_sample: 0
  cuda: True
  beta: 0.0
  interval: 1.0
  r: 6
  name: ncgnn
  gcn: True
  hidden: 128
optim:
  lr: 0.005
  epochs: 500
  
  
