dataset:
  name: amazon_computer
  split: [0.6,0.2,0.2]
train:
  batch_size: 2048
  patience: 5
  repeat: 5
model:
  num_sample: 0
  cuda: True
  beta: 0.0
  interval: 0.3
  r: 7
  name: ncgnn
  gcn: True
  hidden: 128
optim:
  lr: 0.005
  epochs: 500
  
  
