dataset:
  name: academic_py
  split: [0.6,0.2,0.2]
  feature_select: random
train:
  batch_size: 2048
  patience: 3
  repeat: 5
model:
  num_sample: 0
  cuda: True
  beta: 0.0
  interval: 0.0
  r: 1
  name: sage
  gcn: True
  hidden: 128
optim:
  lr: 0.01
  epochs: 500
  
  
